print('Hello World! ' + ScriptTestJS)
console.error("World Hello! " + ScriptTestJS)
console.log.info("Info " + ScriptTestJS)
console.log.error("Error " + ScriptTestJS)
console.log.warn("Warn " + ScriptTestJS)
console.log.trace("Trace " + ScriptTestJS)